- hosts: all

  tasks:

    - name: install packages
      ansible.builtin.package:
        name: 'python3-pip'
        state: present
        update_cache: yes

    - name: install python modules
      pip:
        name: ['docker']

    - name: Deploy redmine application
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: redmine
        image: redmine
        ports:
          - 8080:3000
        env:
          REDMINE_DB_POSTGRES: "{{ app_db_host }}"
          REDMINE_DB_PORT: "{{ app_db_port }}"
          REDMINE_DB_DATABASE: "{{ app_db_database }}"
          REDMINE_DB_USERNAME: "{{ app_db_username }}"
          REDMINE_DB_PASSWORD: "{{ app_db_password }}"

    - name: install and run Datadog agent
      include_role:
        name: datadog.datadog
